/-
Copyright (c) 2026 Dean Cureton. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Dean Cureton
-/
module

public import Mathlib.RingTheory.PuiseuxSeries.Basic
public import Mathlib.RingTheory.Algebraic.Integral

/-!
# Puiseux series are algebraic over Laurent series

This file proves that the field of Puiseux series over a field `K` is algebraic over the field of
Laurent series: the monomial `t ^ (1 / n)` is integral over the image of `K((t))`, being a root of
the monic polynomial `Y ^ n - t`, and the image of `toHahnSeries K n` lies in the subalgebra
generated by this monomial.

## Main results

* `PuiseuxSeries.isIntegral_single_one_div`: the monomial `t ^ (1 / n)` of `HahnSeries ℚ K` is
  integral over the range of `LaurentSeries.toHahnSeries K 1`.
* `PuiseuxSeries.mem_adjoin_single_of_mem_fieldRange`: every element of the range of
  `LaurentSeries.toHahnSeries K n` lies in the subalgebra generated by `t ^ (1 / n)` over the
  range of `LaurentSeries.toHahnSeries K 1`.
* `PuiseuxSeries.isAlgebraic`: `PuiseuxSeries K` is algebraic over `LaurentSeries K`.

## Tags

puiseux series, laurent series, algebraic
-/

@[expose] public section

open LaurentSeries Polynomial

noncomputable section

namespace PuiseuxSeries

variable (K : Type*) [Field K]

/-- The monomial `t ^ (1 / n)` of `HahnSeries ℚ K` is integral over the range of
`LaurentSeries.toHahnSeries K 1`. -/
theorem isIntegral_single_one_div (n : ℕ+) :
    IsIntegral (LaurentSeries.toHahnSeries K 1).fieldRange
      (HahnSeries.single ((1 : ℚ) / (n : ℚ)) (1 : K)) := by
  have hpow : (HahnSeries.single ((1 : ℚ) / (n : ℚ)) (1 : K)) ^ (n : ℕ) =
      HahnSeries.single (1 : ℚ) (1 : K) := by
    simp [HahnSeries.single_pow, one_div, nsmul_eq_mul, n.ne_zero]
  refine ⟨X ^ (n : ℕ) - C ⟨HahnSeries.single (1 : ℚ) (1 : K),
      ⟨HahnSeries.single (1 : ℤ) (1 : K), by simp [toHahnSeries_single]⟩⟩,
    monic_X_pow_sub_C _ n.ne_zero, ?_⟩
  simp only [eval₂_sub, eval₂_X_pow, eval₂_C, hpow]
  exact sub_eq_zero.mpr rfl

/-- Every element of the range of `LaurentSeries.toHahnSeries K n` lies in the subalgebra of
`HahnSeries ℚ K` generated by the monomial `t ^ (1 / n)` over the range of
`LaurentSeries.toHahnSeries K 1`. -/
theorem mem_adjoin_single_of_mem_fieldRange (n : ℕ+) {x : HahnSeries ℚ K}
    (hx : x ∈ (LaurentSeries.toHahnSeries K n).fieldRange) :
    x ∈ Algebra.adjoin (LaurentSeries.toHahnSeries K 1).fieldRange
      {HahnSeries.single ((1 : ℚ) / (n : ℚ)) (1 : K)} := by
  classical
  obtain ⟨f, rfl⟩ := hx
  obtain ⟨b, hb⟩ : BddBelow f.support :=
    f.support.eq_empty_or_nonempty.elim (· ▸ bddBelow_empty)
      fun h ↦ ⟨_, fun _ hy ↦ f.isWF_support.min_le h hy⟩
  have hg : ∀ r : ℤ, ∃ y : LaurentSeries K, ∀ k : ℤ, y.coeff k = f.coeff ((n : ℤ) * k + r) := by
    intro r
    refine ⟨⟨fun k ↦ f.coeff ((n : ℤ) * k + r),
        (BddBelow.isWF ⟨min 0 (b - r), fun k hk ↦ ?_⟩).isPWO⟩, fun _ ↦ rfl⟩
    exact min_le_iff.mpr <| (le_or_gt 0 k).imp id fun h0 ↦ by nlinarith [hb hk, n.pos]
  choose g hgc using hg
  have hexp1 (y : LaurentSeries K) (k : ℤ) : (expand K n y).coeff ((n : ℤ) * k) = y.coeff k :=
    HahnSeries.embDomain_coeff
  have hexp0 (y : LaurentSeries K) {j : ℤ} (hj : ¬∃ k : ℤ, (n : ℤ) * k = j) :
      (expand K n y).coeff j = 0 := HahnSeries.embDomain_of_notMem_range hj
  have hf : f = ∑ r ∈ Finset.range (n : ℕ),
      HahnSeries.single (r : ℤ) (1 : K) * expand K n (g r) := by
    ext j
    rw [HahnSeries.coeff_sum]
    have hn0 : (0 : ℤ) < (n : ℤ) := by exact_mod_cast n.pos
    set r₀ : ℕ := (j % (n : ℤ)).toNat
    have hnonneg := Int.emod_nonneg j (ne_of_gt hn0)
    have hr₀lt : r₀ < (n : ℕ) := (Int.toNat_lt hnonneg).mpr (Int.emod_lt_of_pos j hn0)
    have hr₀cast : (r₀ : ℤ) = j % (n : ℤ) := Int.toNat_of_nonneg hnonneg
    rw [Finset.sum_eq_single_of_mem r₀ (Finset.mem_range.mpr hr₀lt) ?_]
    · have hdiv : j - j % (n : ℤ) = (n : ℤ) * (j / (n : ℤ)) :=
        (Int.mul_ediv_self j (n : ℤ)).symm
      rw [HahnSeries.coeff_single_mul, one_mul, hr₀cast, hdiv, hexp1, hgc]
      exact congrArg _ (by omega)
    · intro r hr hne
      have hnd : ¬∃ k : ℤ, (n : ℤ) * k = j - (r : ℤ) := by
        rintro ⟨k, hk⟩
        have hrlt : (r : ℤ) < (n : ℤ) := by exact_mod_cast Finset.mem_range.mp hr
        refine hne (Nat.cast_injective (R := ℤ) ?_)
        rw [hr₀cast, show j = (n : ℤ) * k + r by omega, Int.mul_add_emod_self_left,
          Int.emod_eq_of_lt (Nat.cast_nonneg _) hrlt]
      rw [HahnSeries.coeff_single_mul, hexp0 _ hnd, mul_zero]
  rw [hf, map_sum]
  refine Subalgebra.sum_mem _ fun r _ ↦ ?_
  have h1 : toHahnSeries K n (HahnSeries.single (r : ℤ) (1 : K)) =
      HahnSeries.single ((1 : ℚ) / (n : ℚ)) (1 : K) ^ r := by
    rw [HahnSeries.single_pow, one_pow, toHahnSeries_single, nsmul_eq_mul, mul_one_div,
      Int.cast_natCast]
  have h2 : toHahnSeries K n (expand K n (g r)) ∈ (toHahnSeries K 1).fieldRange :=
    ⟨g r, by simpa [one_mul] using (DFunLike.congr_fun (toHahnSeries_comp_expand K 1 n) (g r)).symm⟩
  rw [map_mul, h1]
  exact mul_mem (Subalgebra.pow_mem _ (Algebra.self_mem_adjoin_singleton _ _) _)
    (Subalgebra.algebraMap_mem _ (⟨_, h2⟩ : (toHahnSeries K 1).fieldRange))

/-- The field of Puiseux series over a field `K` is algebraic over the field of Laurent
series. -/
instance isAlgebraic : Algebra.IsAlgebraic (LaurentSeries K) (PuiseuxSeries K) where
  isAlgebraic x := by
    let v : PuiseuxSeries K →+* HahnSeries ℚ K := (subfield K).subtype
    obtain ⟨n, hn⟩ := (mem_subfield_iff K).mp x.property
    exact (IsIntegral.isAlgebraic <|
        .of_mem_of_fg _ (isIntegral_single_one_div K n).fg_adjoin_singleton _
          (mem_adjoin_single_of_mem_fieldRange K n hn)).of_ringHom_of_comp_eq
      (toHahnSeries K 1).rangeRestrictFieldEquiv v (EquivLike.surjective _) Subtype.val_injective
      (by ext; rfl)

end PuiseuxSeries
